1.write a program that creates a data frame from a dictionary of ndarrays and lists.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = {'cities':['dindigul','madurai','chennai'],'regnum':[57,58,27]} #{key:value}

In [ ]:
dataframe = pd.DataFrame(data)

In [ ]:
dataframe

     cities  regnum
0  dindigul      57
1   madurai      58
2   chennai      27

In [ ]:
#2. write a program that creates a data frame storing names and marks of students using list of lists (nested list). give relevant name to the columns.

In [ ]:
data2 = [['sasi',89],['amali',90],['dharini',92]]
df2 = pd.DataFrame(data2,columns = ['studname','marks'])
df2

  studname  marks
0     sasi     89
1    amali     90
2  dharini     92

3. write a program to create a dataframe from a dictionary of series

In [ ]:
data3 = {56 : pd.Series(['s','k','g']),57:pd.Series(['s','l','g'])}
df3 = pd.DataFrame(data3)

In [ ]:
df3

  56 57
0  s  s
1  k  l
2  g  g

4. write a program that selects a particular column from the dataframe also add a a new column

In [ ]:
df3[57]

0    s
1    l
2    g
Name: 57, dtype: object

In [ ]:
df3[60] = pd.Series(['j','k','s'])

In [ ]:
df3

  57 60
0  s  j
1  l  k
2  g  s

In [ ]:
df3.pop(56)

0    s
1    k
2    g
Name: 56, dtype: object

In [ ]:
df3[1:2]

  57 60
1  l  k

head, tail,T,axes,dtypes,shape,size,values

In [ ]:
print(df3.axes)

[RangeIndex(start=0, stop=3, step=1), Int64Index([57, 60], dtype='int64')]

In [ ]:
unsorted_df = pd.DataFrame(np.random.randn(5,2),index = [3,4,2,5,1],columns =['a','b'])
unsorted_df
sorted_df = unsorted_df.sort_index()

In [ ]:
sorted_df

          a         b
1  0.860384 -0.471937
2 -0.836961 -0.292809
3  0.292118 -1.745506
4 -0.661269 -1.411693
5 -2.079751 -0.400028

handling missing values

null : nan
zeros are not null

In [ ]:
df4 = pd.DataFrame({1:pd.Series([5,6,7],index = ['a','b','c']), 2:pd.Series([7,8,9,4],index = ['a','b','c','d']),3:pd.Series([80,6],index = ['a','b'])})
df4.shape

(4, 3)

In [ ]:
df4

     1  2     3
a  5.0  7  80.0
b  6.0  8   6.0
c  7.0  9   NaN
d  NaN  4   NaN

In [ ]:
df4.isnull().sum()

1    1
2    0
3    2
dtype: int64

In [ ]:
df4.dropna()

     1  2     3
a  5.0  7  80.0
b  6.0  8   6.0

In [ ]:
#print(df4.add(df6,fill_value=0))

In [ ]:
df4.fillna(6) # replacing null values

     1  2     3
a  5.0  7  80.0
b  6.0  8   6.0
c  7.0  9   6.0
d  6.0  4   6.0

In [ ]:
df3

  57 60
0  s  j
1  l  k
2  g  s

In [ ]:
df3.replace({'s':'yy'})

   57  60
0  yy   j
1   l   k
2   g  yy